import "./globals.css";
import { StateProvider } from "../context/StateContext";
import type { AppProps } from "next/app";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <StateProvider>
      <Component {...pageProps} />
    </StateProvider>
  );
}

export default MyApp;
